export const blogPosts = [
  {
    id: 0,
    title: "Do Client Components in Next.js Really Run Only on the Client?",
    readTime: 8,
    slug: "nextjs-client-components",
    date: "March 1, 2025",
  },
  {
    id: 1,
    title: "Complete Guide to Form Handling in NextJS",
    readTime: 16,
    slug: "form-handling-in-nextjs",
    date: "March 13, 2025",
  },
  {
    id: 2,
    title: "How React Works Behind the Scenes",
    readTime: 22,
    slug: "how-react-works-behind-the-scenes",
    date: "March 22, 2025",
  },
  {
    id: 3,
    title: "Understanding Stateless vs Stateful Architectures",
    readTime: 7,
    slug: "what-is-stateless-and-stateful",
    date: "March 28, 2025",
  },
  {
    id: 4,
    title:
      "How Data Travels the World to Reach Your Screen: A Deep Dive into OSI, TCP/UDP, HTTP, and More",
    readTime: 20,
    slug: "how-data-travels-the-world-to-reach-your-screen",
    date: "April 3, 2025",
  },
  {
    id: 5,
    title: "How JavaScript Works Behind the Scenes",
    readTime: 12,
    slug: "how-javascript-works-behind-the-scenes",
    date: "April 14, 2025",
  },
  {
    id: 6,
    title: "How Node.js Works Behind the Scenes",
    readTime: 19,
    slug: "how-nodejs-works-behind-the-scenes",
    date: "April 25, 2025",
  },
  {
    id: 7,
    title: "How Promises Work in JavaScript",
    readTime: 10,
    slug: "how-promises-work-in-javascript",
    date: "May 3, 2025",
  },
  {
    id: 8,
    title: "How V8 JavaScript Engine Works Behind the Scenes",
    readTime: 15,
    slug: "how-v8-javascript-engine-works-behind-the-scenes",
    date: "May 11, 2025",
  },
  {
    id: 9,
    title: "How Databases Store Your Tables on Disk",
    readTime: 12,
    slug: "how-databases-store-your-tables-on-disk",
    date: "May 25, 2025",
  },
  {
    id: 10,
    title: "How to Create Your Own Simple useState Hook",
    readTime: 9,
    slug: "how-to-create-your-own-simple-use-state-hook",
    date: "June 10, 2025",
  },
];
